In [40]:
import numpy as np

In [41]:
a = np.array([5,6,7])
a

array([5, 6, 7])

In [42]:
a = np.array([[1,2,3],[4,5,6], [7,8,9]])
a.itemsize

4

In [43]:
a = np.array([[1,2,3],[4,5,6], [7,8,9]], dtype = np.float64)
a.itemsize

8

In [44]:
a.size

9

In [45]:
a.shape

(3, 3)

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
i = range(5)
i

range(0, 5)

In [49]:
i[3]

3

In [50]:
array = np.arange(1,100)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [51]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [69]:
a = np.array([[1,2],[4,5], [7,8]])
a

array([[1, 2],
       [4, 5],
       [7, 8]])

In [70]:
a.shape

(3, 2)

In [73]:
a.reshape(2,3)

array([[1, 2, 4],
       [5, 7, 8]])

In [74]:
a.reshape(6,1)

array([[1],
       [2],
       [4],
       [5],
       [7],
       [8]])

In [75]:
a.ravel()

array([1, 2, 4, 5, 7, 8])

In [76]:
a

array([[1, 2],
       [4, 5],
       [7, 8]])

In [77]:
a.min()

1

In [78]:
a.max()

8

In [79]:
a.sum()

27

In [80]:
a.sum(axis=0)

array([12, 15])

In [81]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [2.        , 2.23606798],
       [2.64575131, 2.82842712]])

In [82]:
np.std(a)

2.5

In [84]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [86]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [87]:
a+b

array([[ 6,  8],
       [10, 12]])

In [88]:
a*b

array([[ 5, 12],
       [21, 32]])

In [89]:
a.dot(b)

array([[19, 22],
       [43, 50]])