In [1]:
import numpy as np

In [3]:
n = [ 6, 7, 8 ]
n

[6, 7, 8]

In [5]:
n[1:3]

[7, 8]

In [7]:
a = np.array([6,7,8,9])
a

array([6, 7, 8, 9])

In [9]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [10]:
a[1,2]

3

In [13]:
a[0:2,2]

array([8, 3])

In [14]:
a[-1]

array([9, 3, 2])

In [15]:
a[-1,0:2]

array([9, 3])

In [17]:
a[:, 1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])